<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Country::Create(['iso_cod' => 'AFG', 'name' => 'Afganistán']);
      Country::Create(['iso_cod' => 'ALB', 'name' => 'Albania']);
      Country::Create(['iso_cod' => 'DEU', 'name' => 'Alemania']);
      Country::Create(['iso_cod' => 'DZA', 'name' => 'Algeria']);
      Country::Create(['iso_cod' => 'AND', 'name' => 'Andorra']);
      Country::Create(['iso_cod' => 'AGO', 'name' => 'Angola']);
      Country::Create(['iso_cod' => 'AIA', 'name' => 'Anguila']);
      Country::Create(['iso_cod' => 'ATA', 'name' => 'Antártida']);
      Country::Create(['iso_cod' => 'ATG', 'name' => 'Antigua y Barbuda']);
      Country::Create(['iso_cod' => 'ANT', 'name' => 'Antillas Neerlandesas']);
      Country::Create(['iso_cod' => 'SAU', 'name' => 'Arabia Saudita']);
      Country::Create(['iso_cod' => 'DZA', 'name' => 'Argelia']);
      Country::Create(['iso_cod' => 'ARG', 'name' => 'Argentina']);
      Country::Create(['iso_cod' => 'ARM', 'name' => 'Armenia']);
      Country::Create(['iso_cod' => 'ABW', 'name' => 'Aruba']);
      Country::Create(['iso_cod' => 'AUS', 'name' => 'Australia']);
      Country::Create(['iso_cod' => 'AUT', 'name' => 'Austria']);
      Country::Create(['iso_cod' => 'AZE', 'name' => 'Azerbayán']);
      Country::Create(['iso_cod' => 'BEL', 'name' => 'Bélgica']);
      Country::Create(['iso_cod' => 'BHS', 'name' => 'Bahamas']);
      Country::Create(['iso_cod' => 'BHR', 'name' => 'Bahrein']);
      Country::Create(['iso_cod' => 'BGD', 'name' => 'Bangladesh']);
      Country::Create(['iso_cod' => 'BRB', 'name' => 'Barbados']);
      Country::Create(['iso_cod' => 'BLZ', 'name' => 'Belice']);
      Country::Create(['iso_cod' => 'BEN', 'name' => 'Benín']);
      Country::Create(['iso_cod' => 'BTN', 'name' => 'Bután']);
      Country::Create(['iso_cod' => 'BLR', 'name' => 'Bielorrusia']);
      Country::Create(['iso_cod' => 'BOL', 'name' => 'Bolivia']);
      Country::Create(['iso_cod' => 'BIH', 'name' => 'Bosnia y Herzegovina']);
      Country::Create(['iso_cod' => 'BWA', 'name' => 'Botsuana']);
      Country::Create(['iso_cod' => 'BRA', 'name' => 'Brasil']);
      Country::Create(['iso_cod' => 'BRN', 'name' => 'Brunéi']);
      Country::Create(['iso_cod' => 'BGR', 'name' => 'Bulgaria']);
      Country::Create(['iso_cod' => 'BFA', 'name' => 'Burkina Faso']);
      Country::Create(['iso_cod' => 'BDI', 'name' => 'Burundi']);
      Country::Create(['iso_cod' => 'CPV', 'name' => 'Cabo Verde']);
      Country::Create(['iso_cod' => 'KHM', 'name' => 'Camboya']);
      Country::Create(['iso_cod' => 'CMR', 'name' => 'Camerún']);
      Country::Create(['iso_cod' => 'CAN', 'name' => 'Canadá']);
      Country::Create(['iso_cod' => 'TCD', 'name' => 'Chad']);
      Country::Create(['iso_cod' => 'CHL', 'name' => 'Chile']);
      Country::Create(['iso_cod' => 'CHN', 'name' => 'China']);
      Country::Create(['iso_cod' => 'CYP', 'name' => 'Chipre']);
      Country::Create(['iso_cod' => 'VAT', 'name' => 'Ciudad del Vaticano']);
      Country::Create(['iso_cod' => 'COL', 'name' => 'Colombia']);
      Country::Create(['iso_cod' => 'COM', 'name' => 'Comoras']);
      Country::Create(['iso_cod' => 'COG', 'name' => 'Congo']);
      Country::Create(['iso_cod' => 'PRK', 'name' => 'Corea del Norte']);
      Country::Create(['iso_cod' => 'KOR', 'name' => 'Corea del Sur']);
      Country::Create(['iso_cod' => 'CIV', 'name' => 'Costa de Marfil']);
      Country::Create(['iso_cod' => 'CRI', 'name' => 'Costa Rica']);
      Country::Create(['iso_cod' => 'HRV', 'name' => 'Croacia']);
      Country::Create(['iso_cod' => 'CUB', 'name' => 'Cuba']);
      Country::Create(['iso_cod' => 'DNK', 'name' => 'Dinamarca']);
      Country::Create(['iso_cod' => 'DMA', 'name' => 'Dominica']);
      Country::Create(['iso_cod' => 'ECU', 'name' => 'Ecuador']);
      Country::Create(['iso_cod' => 'EGY', 'name' => 'Egipto']);
      Country::Create(['iso_cod' => 'SLV', 'name' => 'El Salvador']);
      Country::Create(['iso_cod' => 'ARE', 'name' => 'Emiratos Árabes Unidos']);
      Country::Create(['iso_cod' => 'ERI', 'name' => 'Eritrea']);
      Country::Create(['iso_cod' => 'SVK', 'name' => 'Eslovaquia']);
      Country::Create(['iso_cod' => 'SVN', 'name' => 'Eslovenia']);
      Country::Create(['iso_cod' => 'ESP', 'name' => 'España']);
      Country::Create(['iso_cod' => 'USA', 'name' => 'Estados Unidos de América']);
      Country::Create(['iso_cod' => 'EST', 'name' => 'Estonia']);
      Country::Create(['iso_cod' => 'ETH', 'name' => 'Etiopía']);
      Country::Create(['iso_cod' => 'PHL', 'name' => 'Filipinas']);
      Country::Create(['iso_cod' => 'FIN', 'name' => 'Finlandia']);
      Country::Create(['iso_cod' => 'FJI', 'name' => 'Fiyi']);
      Country::Create(['iso_cod' => 'FRA', 'name' => 'Francia']);
      Country::Create(['iso_cod' => 'GAB', 'name' => 'Gabón']);
      Country::Create(['iso_cod' => 'GMB', 'name' => 'Gambia']);
      Country::Create(['iso_cod' => 'GEO', 'name' => 'Georgia']);
      Country::Create(['iso_cod' => 'GHA', 'name' => 'Ghana']);
      Country::Create(['iso_cod' => 'GIB', 'name' => 'Gibraltar']);
      Country::Create(['iso_cod' => 'GRD', 'name' => 'Granada']);
      Country::Create(['iso_cod' => 'GRC', 'name' => 'Grecia']);
      Country::Create(['iso_cod' => 'GRL', 'name' => 'Groenlandia']);
      Country::Create(['iso_cod' => 'GLP', 'name' => 'Guadalupe']);
      Country::Create(['iso_cod' => 'GUM', 'name' => 'Guam']);
      Country::Create(['iso_cod' => 'GTM', 'name' => 'Guatemala']);
      Country::Create(['iso_cod' => 'GUF', 'name' => 'Guayana Francesa']);
      Country::Create(['iso_cod' => 'GGY', 'name' => 'Guernsey']);
      Country::Create(['iso_cod' => 'GIN', 'name' => 'Guinea']);
      Country::Create(['iso_cod' => 'GNQ', 'name' => 'Guinea Ecuatorial']);
      Country::Create(['iso_cod' => 'GNB', 'name' => 'Guinea-Bissau']);
      Country::Create(['iso_cod' => 'GUY', 'name' => 'Guyana']);
      Country::Create(['iso_cod' => 'HTI', 'name' => 'Haití']);
      Country::Create(['iso_cod' => 'HND', 'name' => 'Honduras']);
      Country::Create(['iso_cod' => 'HKG', 'name' => 'Hong kong']);
      Country::Create(['iso_cod' => 'HUN', 'name' => 'Hungría']);
      Country::Create(['iso_cod' => 'IND', 'name' => 'India']);
      Country::Create(['iso_cod' => 'IDN', 'name' => 'Indonesia']);
      Country::Create(['iso_cod' => 'IRN', 'name' => 'Irán']);
      Country::Create(['iso_cod' => 'IRQ', 'name' => 'Irak']);
      Country::Create(['iso_cod' => 'IRL', 'name' => 'Irlanda']);
      Country::Create(['iso_cod' => 'BVT', 'name' => 'Isla Bouvet']);
      Country::Create(['iso_cod' => 'IMN', 'name' => 'Isla de Man']);
      Country::Create(['iso_cod' => 'CXR', 'name' => 'Isla de Navidad']);
      Country::Create(['iso_cod' => 'NFK', 'name' => 'Isla Norfolk']);
      Country::Create(['iso_cod' => 'ISL', 'name' => 'Islandia']);
      Country::Create(['iso_cod' => 'BMU', 'name' => 'Islas Bermudas']);
      Country::Create(['iso_cod' => 'CYM', 'name' => 'Islas Caimán']);
      Country::Create(['iso_cod' => 'CCK', 'name' => 'Islas Cocos (Keeling)']);
      Country::Create(['iso_cod' => 'COK', 'name' => 'Islas Cook']);
      Country::Create(['iso_cod' => 'ALA', 'name' => 'Islas de Åland']);
      Country::Create(['iso_cod' => 'FRO', 'name' => 'Islas Faroe']);
      Country::Create(['iso_cod' => 'SGS', 'name' => 'Islas Georgias del Sur y Sandwich del Sur']);
      Country::Create(['iso_cod' => 'HMD', 'name' => 'Islas Heard y McDonald']);
      Country::Create(['iso_cod' => 'FLK', 'name' => 'Islas Maldivas']);
      Country::Create(['iso_cod' => 'MNP', 'name' => 'Islas Marianas del Norte']);
      Country::Create(['iso_cod' => 'MHL', 'name' => 'Islas Marshall']);
      Country::Create(['iso_cod' => 'PCN', 'name' => 'Islas Pitcairn']);
      Country::Create(['iso_cod' => 'SLB', 'name' => 'Islas Salomón']);
      Country::Create(['iso_cod' => 'TCA', 'name' => 'Islas Turcas y Caicos']);
      Country::Create(['iso_cod' => 'UMI', 'name' => 'Islas Ultramarinas Menores de Estados Unidos']);
      Country::Create(['iso_cod' => 'VGB', 'name' => 'Islas Vírgenes Británicas']);
      Country::Create(['iso_cod' => 'VIR', 'name' => 'Islas Vírgenes de los Estados Unidos']);
      Country::Create(['iso_cod' => 'ISR', 'name' => 'Israel']);
      Country::Create(['iso_cod' => 'ITA', 'name' => 'Italia']);
      Country::Create(['iso_cod' => 'JAM', 'name' => 'Jamaica']);
      Country::Create(['iso_cod' => 'JPN', 'name' => 'Japón']);
      Country::Create(['iso_cod' => 'JEY', 'name' => 'Jersey']);
      Country::Create(['iso_cod' => 'JOR', 'name' => 'Jordania']);
      Country::Create(['iso_cod' => 'KAZ', 'name' => 'Kazajistán']);
      Country::Create(['iso_cod' => 'KEN', 'name' => 'Kenia']);
      Country::Create(['iso_cod' => 'KGZ', 'name' => 'Kirgizstán']);
      Country::Create(['iso_cod' => 'KIR', 'name' => 'Kiribati']);
      Country::Create(['iso_cod' => 'KWT', 'name' => 'Kuwait']);
      Country::Create(['iso_cod' => 'LBN', 'name' => 'Líbano']);
      Country::Create(['iso_cod' => 'LAO', 'name' => 'Laos']);
      Country::Create(['iso_cod' => 'LSO', 'name' => 'Lesoto']);
      Country::Create(['iso_cod' => 'LVA', 'name' => 'Letonia']);
      Country::Create(['iso_cod' => 'LBR', 'name' => 'Liberia']);
      Country::Create(['iso_cod' => 'LBY', 'name' => 'Libia']);
      Country::Create(['iso_cod' => 'LIE', 'name' => 'Liechtenstein']);
      Country::Create(['iso_cod' => 'LTU', 'name' => 'Lituania']);
      Country::Create(['iso_cod' => 'LUX', 'name' => 'Luxemburgo']);
      Country::Create(['iso_cod' => 'MEX', 'name' => 'México']);
      Country::Create(['iso_cod' => 'MCO', 'name' => 'Mónaco']);
      Country::Create(['iso_cod' => 'MAC', 'name' => 'Macao']);
      Country::Create(['iso_cod' => 'MKD', 'name' => 'Macedônia']);
      Country::Create(['iso_cod' => 'MDG', 'name' => 'Madagascar']);
      Country::Create(['iso_cod' => 'MYS', 'name' => 'Malasia']);
      Country::Create(['iso_cod' => 'MWI', 'name' => 'Malawi']);
      Country::Create(['iso_cod' => 'MLI', 'name' => 'Mali']);
      Country::Create(['iso_cod' => 'MLT', 'name' => 'Malta']);
      Country::Create(['iso_cod' => 'MAR', 'name' => 'Marruecos']);
      Country::Create(['iso_cod' => 'MTQ', 'name' => 'Martinica']);
      Country::Create(['iso_cod' => 'MUS', 'name' => 'Mauricio']);
      Country::Create(['iso_cod' => 'MRT', 'name' => 'Mauritania']);
      Country::Create(['iso_cod' => 'MYT', 'name' => 'Mayotte']);
      Country::Create(['iso_cod' => 'FSM', 'name' => 'Micronesia']);
      Country::Create(['iso_cod' => 'MDA', 'name' => 'Moldavia']);
      Country::Create(['iso_cod' => 'MNG', 'name' => 'Mongolia']);
      Country::Create(['iso_cod' => 'MNE', 'name' => 'Montenegro']);
      Country::Create(['iso_cod' => 'MSR', 'name' => 'Montserrat']);
      Country::Create(['iso_cod' => 'MOZ', 'name' => 'Mozambique']);
      Country::Create(['iso_cod' => 'MMR', 'name' => 'Myanmar']);
      Country::Create(['iso_cod' => 'NAM', 'name' => 'Namibia']);
      Country::Create(['iso_cod' => 'NRU', 'name' => 'Nauru']);
      Country::Create(['iso_cod' => 'NPL', 'name' => 'Nepal']);
      Country::Create(['iso_cod' => 'NIC', 'name' => 'Nicaragua']);
      Country::Create(['iso_cod' => 'NER', 'name' => 'Niger']);
      Country::Create(['iso_cod' => 'NGA', 'name' => 'Nigeria']);
      Country::Create(['iso_cod' => 'NIU', 'name' => 'Niue']);
      Country::Create(['iso_cod' => 'NOR', 'name' => 'Noruega']);
      Country::Create(['iso_cod' => 'NCL', 'name' => 'Nueva Caledonia']);
      Country::Create(['iso_cod' => 'NZL', 'name' => 'Nueva Zelanda']);
      Country::Create(['iso_cod' => 'OMN', 'name' => 'Omán']);
      Country::Create(['iso_cod' => 'NLD', 'name' => 'Países Bajos']);
      Country::Create(['iso_cod' => 'PAK', 'name' => 'Pakistán']);
      Country::Create(['iso_cod' => 'PLW', 'name' => 'Palau']);
      Country::Create(['iso_cod' => 'PSE', 'name' => 'Palestina']);
      Country::Create(['iso_cod' => 'PAN', 'name' => 'Panamá']);
      Country::Create(['iso_cod' => 'PNG', 'name' => 'Papúa Nueva Guinea']);
      Country::Create(['iso_cod' => 'PRY', 'name' => 'Paraguay']);
      Country::Create(['iso_cod' => 'PER', 'name' => 'Perú']);
      Country::Create(['iso_cod' => 'PYF', 'name' => 'Polinesia Francesa']);
      Country::Create(['iso_cod' => 'POL', 'name' => 'Polonia']);
      Country::Create(['iso_cod' => 'PRT', 'name' => 'Portugal']);
      Country::Create(['iso_cod' => 'PRI', 'name' => 'Puerto Rico']);
      Country::Create(['iso_cod' => 'QAT', 'name' => 'Qatar']);
      Country::Create(['iso_cod' => 'GBR', 'name' => 'Reino Unido']);
      Country::Create(['iso_cod' => 'COG', 'name' => 'República del Congo']);
      Country::Create(['iso_cod' => 'CAF', 'name' => 'República Centroafricana']);
      Country::Create(['iso_cod' => 'CZE', 'name' => 'República Checa']);
      Country::Create(['iso_cod' => 'DOM', 'name' => 'República Dominicana']);
      Country::Create(['iso_cod' => 'REU', 'name' => 'Reunión']);
      Country::Create(['iso_cod' => 'RWA', 'name' => 'Ruanda']);
      Country::Create(['iso_cod' => 'ROU', 'name' => 'Rumanía']);
      Country::Create(['iso_cod' => 'RUS', 'name' => 'Rusia']);
      Country::Create(['iso_cod' => 'ESH', 'name' => 'Sahara Occidental']);
      Country::Create(['iso_cod' => 'WSM', 'name' => 'Samoa']);
      Country::Create(['iso_cod' => 'ASM', 'name' => 'Samoa Americana']);
      Country::Create(['iso_cod' => 'KNA', 'name' => 'San Cristóbal y Nieves']);
      Country::Create(['iso_cod' => 'SMR', 'name' => 'San Marino']);
      Country::Create(['iso_cod' => 'SPM', 'name' => 'San Pedro y Miquelón']);
      Country::Create(['iso_cod' => 'VCT', 'name' => 'San Vicente y las Granadinas']);
      Country::Create(['iso_cod' => 'SHN', 'name' => 'Santa Elena']);
      Country::Create(['iso_cod' => 'LCA', 'name' => 'Santa Lucía']);
      Country::Create(['iso_cod' => 'STP', 'name' => 'Santo Tomé y Príncipe']);
      Country::Create(['iso_cod' => 'SEN', 'name' => 'Senegal']);
      Country::Create(['iso_cod' => 'SRB', 'name' => 'Serbia']);
      Country::Create(['iso_cod' => 'SYC', 'name' => 'Seychelles']);
      Country::Create(['iso_cod' => 'SLE', 'name' => 'Sierra Leona']);
      Country::Create(['iso_cod' => 'SGP', 'name' => 'Singapur']);
      Country::Create(['iso_cod' => 'SYR', 'name' => 'Siria']);
      Country::Create(['iso_cod' => 'SOM', 'name' => 'Somalia']);
      Country::Create(['iso_cod' => 'LKA', 'name' => 'Sri lanka']);
      Country::Create(['iso_cod' => 'ZAF', 'name' => 'Sudáfrica']);
      Country::Create(['iso_cod' => 'SDN', 'name' => 'Sudán']);
      Country::Create(['iso_cod' => 'SWE', 'name' => 'Suecia']);
      Country::Create(['iso_cod' => 'CHE', 'name' => 'Suiza']);
      Country::Create(['iso_cod' => 'SUR', 'name' => 'Surinám']);
      Country::Create(['iso_cod' => 'SJM', 'name' => 'Svalbard y Jan Mayen']);
      Country::Create(['iso_cod' => 'SWZ', 'name' => 'Swazilandia']);
      Country::Create(['iso_cod' => 'TJK', 'name' => 'Tayikistán']);
      Country::Create(['iso_cod' => 'TZA', 'name' => 'Tailandia']);
      Country::Create(['iso_cod' => 'TWN', 'name' => 'Taiwán']);
      Country::Create(['iso_cod' => 'TZA', 'name' => 'Tanzania']);
      Country::Create(['iso_cod' => 'IOT', 'name' => 'Territorio Británico del Océano Índico']);
      Country::Create(['iso_cod' => 'ATF', 'name' => 'Territorios Australes y Antárticas Franceses']);
      Country::Create(['iso_cod' => 'TLS', 'name' => 'Timor Oriental']);
      Country::Create(['iso_cod' => 'TGO', 'name' => 'Togo']);
      Country::Create(['iso_cod' => 'TKL', 'name' => 'Tokelau']);
      Country::Create(['iso_cod' => 'TON', 'name' => 'Tonga']);
      Country::Create(['iso_cod' => 'TTO', 'name' => 'Trinidad y Tobago']);
      Country::Create(['iso_cod' => 'TUN', 'name' => 'Tunez']);
      Country::Create(['iso_cod' => 'TKM', 'name' => 'Turkmenistán']);
      Country::Create(['iso_cod' => 'TUR', 'name' => 'Turquía']);
      Country::Create(['iso_cod' => 'TUV', 'name' => 'Tuvalu']);
      Country::Create(['iso_cod' => 'UKR', 'name' => 'Ucrania']);
      Country::Create(['iso_cod' => 'UGA', 'name' => 'Uganda']);
      Country::Create(['iso_cod' => 'URY', 'name' => 'Uruguay']);
      Country::Create(['iso_cod' => 'UZB', 'name' => 'Uzbekistán']);
      Country::Create(['iso_cod' => 'VUT', 'name' => 'Vanuatu']);
      Country::Create(['iso_cod' => 'VEN', 'name' => 'Venezuela']);
      Country::Create(['iso_cod' => 'VNM', 'name' => 'Vietnam']);
      Country::Create(['iso_cod' => 'WLF', 'name' => 'Wallis y Futuna']);
      Country::Create(['iso_cod' => 'YEM', 'name' => 'Yemen']);
      Country::Create(['iso_cod' => 'DJI', 'name' => 'Yibuti']);
      Country::Create(['iso_cod' => 'ZMB', 'name' => 'Zambia']);
      Country::Create(['iso_cod' => 'ZWE', 'name' => 'Zimbabue']);
    }
}
