<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Country::Create(['id_minsal' => 'AFG', 'name' => 'Afganistán']);
      Country::Create(['id_minsal' => 'ALB', 'name' => 'Albania']);
      Country::Create(['id_minsal' => 'DEU', 'name' => 'Alemania']);
      Country::Create(['id_minsal' => 'DZA', 'name' => 'Algeria']);
      Country::Create(['id_minsal' => 'AND', 'name' => 'Andorra']);
      Country::Create(['id_minsal' => 'AGO', 'name' => 'Angola']);
      Country::Create(['id_minsal' => 'AIA', 'name' => 'Anguila']);
      Country::Create(['id_minsal' => 'ATA', 'name' => 'Antártida']);
      Country::Create(['id_minsal' => 'ATG', 'name' => 'Antigua y Barbuda']);
      Country::Create(['id_minsal' => '', 'name' => 'Antillas Neerlandesas']);
      Country::Create(['id_minsal' => '', 'name' => 'Arabia Saudita']);
      Country::Create(['id_minsal' => 'DZA', 'name' => 'Argelia']);
      Country::Create(['id_minsal' => 'ARG', 'name' => 'Argentina']);
      Country::Create(['id_minsal' => 'ARM', 'name' => 'Armenia']);
      Country::Create(['id_minsal' => 'ABW', 'name' => 'Aruba']);
      Country::Create(['id_minsal' => 'AUS', 'name' => 'Australia']);
      Country::Create(['id_minsal' => 'AUT', 'name' => 'Austria']);
      Country::Create(['id_minsal' => 'AZE', 'name' => 'Azerbayán']);
      Country::Create(['id_minsal' => 'BEL', 'name' => 'Bélgica']);
      Country::Create(['id_minsal' => 'BHS', 'name' => 'Bahamas']);
      Country::Create(['id_minsal' => 'BHR', 'name' => 'Bahrein']);
      Country::Create(['id_minsal' => 'BGD', 'name' => 'Bangladesh']);
      Country::Create(['id_minsal' => 'BRB', 'name' => 'Barbados']);
      Country::Create(['id_minsal' => 'BLZ', 'name' => 'Belice']);
      Country::Create(['id_minsal' => 'BEN', 'name' => 'Benín']);
      Country::Create(['id_minsal' => 'BTN', 'name' => 'Bután']);
      Country::Create(['id_minsal' => '', 'name' => 'Bielorrusia']);
      Country::Create(['id_minsal' => '', 'name' => 'Birmania']);
      Country::Create(['id_minsal' => '068', 'name' => 'Bolivia']);
      Country::Create(['id_minsal' => '070', 'name' => 'Bosnia y Herzegovina']);
      Country::Create(['id_minsal' => '072', 'name' => 'Botsuana']);
      Country::Create(['id_minsal' => '076', 'name' => 'Brasil']);
      Country::Create(['id_minsal' => '096', 'name' => 'Brunéi']);
      Country::Create(['id_minsal' => '100', 'name' => 'Bulgaria']);
      Country::Create(['id_minsal' => '854', 'name' => 'Burkina Faso']);
      Country::Create(['id_minsal' => '108', 'name' => 'Burundi']);
      Country::Create(['id_minsal' => '132', 'name' => 'Cabo Verde']);
      Country::Create(['id_minsal' => '116', 'name' => 'Camboya']);
      Country::Create(['id_minsal' => '120', 'name' => 'Camerún']);
      Country::Create(['id_minsal' => '124', 'name' => 'Canadá']);
      Country::Create(['id_minsal' => '148', 'name' => 'Chad']);
      Country::Create(['id_minsal' => '152', 'name' => 'Chile']);
      Country::Create(['id_minsal' => '156', 'name' => 'China']);
      Country::Create(['id_minsal' => '196', 'name' => 'Chipre']);
      Country::Create(['id_minsal' => '336', 'name' => 'Ciudad del Vaticano']);
      Country::Create(['id_minsal' => '170', 'name' => 'Colombia']);
      Country::Create(['id_minsal' => '174', 'name' => 'Comoras']);
      Country::Create(['id_minsal' => '178', 'name' => 'Congo']);
      Country::Create(['id_minsal' => '408', 'name' => 'Corea del Norte']);
      Country::Create(['id_minsal' => '410', 'name' => 'Corea del Sur']);
      Country::Create(['id_minsal' => '384', 'name' => 'Costa de Marfil']);
      Country::Create(['id_minsal' => '188', 'name' => 'Costa Rica']);
      Country::Create(['id_minsal' => '191', 'name' => 'Croacia']);
      Country::Create(['id_minsal' => '192', 'name' => 'Cuba']);
      Country::Create(['id_minsal' => '208', 'name' => 'Dinamarca']);
      Country::Create(['id_minsal' => '212', 'name' => 'Dominica']);
      Country::Create(['id_minsal' => '218', 'name' => 'Ecuador']);
      Country::Create(['id_minsal' => '818', 'name' => 'Egipto']);
      Country::Create(['id_minsal' => '222', 'name' => 'El Salvador']);
      Country::Create(['id_minsal' => '784', 'name' => 'Emiratos Árabes Unidos']);
      Country::Create(['id_minsal' => '232', 'name' => 'Eritrea']);
      Country::Create(['id_minsal' => '703', 'name' => 'Eslovaquia']);
      Country::Create(['id_minsal' => '705', 'name' => 'Eslovenia']);
      Country::Create(['id_minsal' => '724', 'name' => 'España']);
      Country::Create(['id_minsal' => '518', 'name' => 'Estados Unidos de América']);
      Country::Create(['id_minsal' => '233', 'name' => 'Estonia']);
      Country::Create(['id_minsal' => '231', 'name' => 'Etiopía']);
      Country::Create(['id_minsal' => '608', 'name' => 'Filipinas']);
      Country::Create(['id_minsal' => '246', 'name' => 'Finlandia']);
      Country::Create(['id_minsal' => '242', 'name' => 'Fiyi']);
      Country::Create(['id_minsal' => '250', 'name' => 'Francia']);
      Country::Create(['id_minsal' => '266', 'name' => 'Gabón']);
      Country::Create(['id_minsal' => '270', 'name' => 'Gambia']);
      Country::Create(['id_minsal' => '268', 'name' => 'Georgia']);
      Country::Create(['id_minsal' => '288', 'name' => 'Ghana']);
      Country::Create(['id_minsal' => '292', 'name' => 'Gibraltar']);
      Country::Create(['id_minsal' => '308', 'name' => 'Granada']);
      Country::Create(['id_minsal' => '300', 'name' => 'Grecia']);
      Country::Create(['id_minsal' => '304', 'name' => 'Groenlandia']);
      Country::Create(['id_minsal' => '312', 'name' => 'Guadalupe']);
      Country::Create(['id_minsal' => '316', 'name' => 'Guam']);
      Country::Create(['id_minsal' => '320', 'name' => 'Guatemala']);
      Country::Create(['id_minsal' => '254', 'name' => 'Guayana Francesa']);
      Country::Create(['id_minsal' => '831', 'name' => 'Guernsey']);
      Country::Create(['id_minsal' => '324', 'name' => 'Guinea']);
      Country::Create(['id_minsal' => '226', 'name' => 'Guinea Ecuatorial']);
      Country::Create(['id_minsal' => '624', 'name' => 'Guinea-Bissau']);
      Country::Create(['id_minsal' => '328', 'name' => 'Guyana']);
      Country::Create(['id_minsal' => '332', 'name' => 'Haití']);
      Country::Create(['id_minsal' => '340', 'name' => 'Honduras']);
      Country::Create(['id_minsal' => '344', 'name' => 'Hong kong']);
      Country::Create(['id_minsal' => '348', 'name' => 'Hungría']);
      Country::Create(['id_minsal' => '356', 'name' => 'India']);
      Country::Create(['id_minsal' => '360', 'name' => 'Indonesia']);
      Country::Create(['id_minsal' => '364', 'name' => 'Irán']);
      Country::Create(['id_minsal' => '368', 'name' => 'Irak']);
      Country::Create(['id_minsal' => '372', 'name' => 'Irlanda']);
      Country::Create(['id_minsal' => '556', 'name' => 'Isla Bouvet']);
      Country::Create(['id_minsal' => '557', 'name' => 'Isla de Man']);
      Country::Create(['id_minsal' => '558', 'name' => 'Isla de Navidad']);
      Country::Create(['id_minsal' => '559', 'name' => 'Isla Norfolk']);
      Country::Create(['id_minsal' => '352', 'name' => 'Islandia']);
      Country::Create(['id_minsal' => '561', 'name' => 'Islas Bermudas']);
      Country::Create(['id_minsal' => '562', 'name' => 'Islas Caimán']);
      Country::Create(['id_minsal' => '563', 'name' => 'Islas Cocos (Keeling)']);
      Country::Create(['id_minsal' => '184', 'name' => 'Islas Cook']);
      Country::Create(['id_minsal' => '565', 'name' => 'Islas de Åland']);
      Country::Create(['id_minsal' => '234', 'name' => 'Islas Feroe']);
      Country::Create(['id_minsal' => '239', 'name' => 'Islas Georgias del Sur y Sandwich del Sur']);
      Country::Create(['id_minsal' => '334', 'name' => 'Islas Heard y McDonald']);
      Country::Create(['id_minsal' => '462', 'name' => 'Islas Maldivas']);
      Country::Create(['id_minsal' => '238', 'name' => 'Islas Malvinas']);
      Country::Create(['id_minsal' => '581', 'name' => 'Islas Marianas del Norte']);
      Country::Create(['id_minsal' => '584', 'name' => 'Islas Marshall']);
      Country::Create(['id_minsal' => '612', 'name' => 'Islas Pitcairn']);
      Country::Create(['id_minsal' => '090', 'name' => 'Islas Salomón']);
      Country::Create(['id_minsal' => '796', 'name' => 'Islas Turcas y Caicos']);
      Country::Create(['id_minsal' => '581', 'name' => 'Islas Ultramarinas Menores de Estados Unidos']);
      Country::Create(['id_minsal' => '092', 'name' => 'Islas Vírgenes Británicas']);
      Country::Create(['id_minsal' => '850', 'name' => 'Islas Vírgenes de los Estados Unidos']);
      Country::Create(['id_minsal' => '376', 'name' => 'Israel']);
      Country::Create(['id_minsal' => '380', 'name' => 'Italia']);
      Country::Create(['id_minsal' => '388', 'name' => 'Jamaica']);
      Country::Create(['id_minsal' => '392', 'name' => 'Japón']);
      Country::Create(['id_minsal' => '832', 'name' => 'Jersey']);
      Country::Create(['id_minsal' => '400', 'name' => 'Jordania']);
      Country::Create(['id_minsal' => '398', 'name' => 'Kazajistán']);
      Country::Create(['id_minsal' => '404', 'name' => 'Kenia']);
      Country::Create(['id_minsal' => '417', 'name' => 'Kirgizstán']);
      Country::Create(['id_minsal' => '296', 'name' => 'Kiribati']);
      Country::Create(['id_minsal' => '414', 'name' => 'Kuwait']);
      Country::Create(['id_minsal' => '422', 'name' => 'Líbano']);
      Country::Create(['id_minsal' => '418', 'name' => 'Laos']);
      Country::Create(['id_minsal' => '426', 'name' => 'Lesoto']);
      Country::Create(['id_minsal' => '428', 'name' => 'Letonia']);
      Country::Create(['id_minsal' => '430', 'name' => 'Liberia']);
      Country::Create(['id_minsal' => '434', 'name' => 'Libia']);
      Country::Create(['id_minsal' => '438', 'name' => 'Liechtenstein']);
      Country::Create(['id_minsal' => '440', 'name' => 'Lituania']);
      Country::Create(['id_minsal' => '442', 'name' => 'Luxemburgo']);
      Country::Create(['id_minsal' => '484', 'name' => 'México']);
      Country::Create(['id_minsal' => '492', 'name' => 'Mónaco']);
      Country::Create(['id_minsal' => '446', 'name' => 'Macao']);
      Country::Create(['id_minsal' => '807', 'name' => 'Macedônia']);
      Country::Create(['id_minsal' => '450', 'name' => 'Madagascar']);
      Country::Create(['id_minsal' => '458', 'name' => 'Malasia']);
      Country::Create(['id_minsal' => '454', 'name' => 'Malawi']);
      Country::Create(['id_minsal' => '466', 'name' => 'Mali']);
      Country::Create(['id_minsal' => '470', 'name' => 'Malta']);
      Country::Create(['id_minsal' => '504', 'name' => 'Marruecos']);
      Country::Create(['id_minsal' => '474', 'name' => 'Martinica']);
      Country::Create(['id_minsal' => '480', 'name' => 'Mauricio']);
      Country::Create(['id_minsal' => '478', 'name' => 'Mauritania']);
      Country::Create(['id_minsal' => '175', 'name' => 'Mayotte']);
      Country::Create(['id_minsal' => '583', 'name' => 'Micronesia']);
      Country::Create(['id_minsal' => '498', 'name' => 'Moldavia']);
      Country::Create(['id_minsal' => '496', 'name' => 'Mongolia']);
      Country::Create(['id_minsal' => '499', 'name' => 'Montenegro']);
      Country::Create(['id_minsal' => '500', 'name' => 'Montserrat']);
      Country::Create(['id_minsal' => '508', 'name' => 'Mozambique']);
      Country::Create(['id_minsal' => '104', 'name' => 'Myanmar']);
      Country::Create(['id_minsal' => '516', 'name' => 'Namibia']);
      Country::Create(['id_minsal' => '520', 'name' => 'Nauru']);
      Country::Create(['id_minsal' => '524', 'name' => 'Nepal']);
      Country::Create(['id_minsal' => '558', 'name' => 'Nicaragua']);
      Country::Create(['id_minsal' => '562', 'name' => 'Niger']);
      Country::Create(['id_minsal' => '566', 'name' => 'Nigeria']);
      Country::Create(['id_minsal' => '570', 'name' => 'Niue']);
      Country::Create(['id_minsal' => '574', 'name' => 'Norfolk']);
      Country::Create(['id_minsal' => '578', 'name' => 'Noruega']);
      Country::Create(['id_minsal' => '540', 'name' => 'Nueva Caledonia']);
      Country::Create(['id_minsal' => '554', 'name' => 'Nueva Zelanda']);
      Country::Create(['id_minsal' => '512', 'name' => 'Omán']);
      Country::Create(['id_minsal' => '528', 'name' => 'Países Bajos']);
      Country::Create(['id_minsal' => '586', 'name' => 'Pakistán']);
      Country::Create(['id_minsal' => '585', 'name' => 'Palau']);
      Country::Create(['id_minsal' => '275', 'name' => 'Palestina']);
      Country::Create(['id_minsal' => '591', 'name' => 'Panamá']);
      Country::Create(['id_minsal' => '598', 'name' => 'Papúa Nueva Guinea']);
      Country::Create(['id_minsal' => '600', 'name' => 'Paraguay']);
      Country::Create(['id_minsal' => '604', 'name' => 'Perú']);
      Country::Create(['id_minsal' => '258', 'name' => 'Polinesia Francesa']);
      Country::Create(['id_minsal' => '616', 'name' => 'Polonia']);
      Country::Create(['id_minsal' => '620', 'name' => 'Portugal']);
      Country::Create(['id_minsal' => '630', 'name' => 'Puerto Rico']);
      Country::Create(['id_minsal' => '634', 'name' => 'Qatar']);
      Country::Create(['id_minsal' => '826', 'name' => 'Reino Unido']);
      Country::Create(['id_minsal' => '180', 'name' => 'República del Congo']);
      Country::Create(['id_minsal' => '140', 'name' => 'República Centroafricana']);
      Country::Create(['id_minsal' => '203', 'name' => 'República Checa']);
      Country::Create(['id_minsal' => '214', 'name' => 'República Dominicana']);
      Country::Create(['id_minsal' => '638', 'name' => 'Reunión']);
      Country::Create(['id_minsal' => '646', 'name' => 'Ruanda']);
      Country::Create(['id_minsal' => '642', 'name' => 'Rumanía']);
      Country::Create(['id_minsal' => '643', 'name' => 'Rusia']);
      Country::Create(['id_minsal' => '732', 'name' => 'Sahara Occidental']);
      Country::Create(['id_minsal' => '882', 'name' => 'Samoa']);
      Country::Create(['id_minsal' => '016', 'name' => 'Samoa Americana']);
      Country::Create(['id_minsal' => '659', 'name' => 'San Cristóbal y Nieves']);
      Country::Create(['id_minsal' => '674', 'name' => 'San Marino']);
      Country::Create(['id_minsal' => '666', 'name' => 'San Pedro y Miquelón']);
      Country::Create(['id_minsal' => '670', 'name' => 'San Vicente y las Granadinas']);
      Country::Create(['id_minsal' => '654', 'name' => 'Santa Elena']);
      Country::Create(['id_minsal' => '662', 'name' => 'Santa Lucía']);
      Country::Create(['id_minsal' => '678', 'name' => 'Santo Tomé y Príncipe']);
      Country::Create(['id_minsal' => '686', 'name' => 'Senegal']);
      Country::Create(['id_minsal' => '688', 'name' => 'Serbia']);
      Country::Create(['id_minsal' => '690', 'name' => 'Seychelles']);
      Country::Create(['id_minsal' => '694', 'name' => 'Sierra Leona']);
      Country::Create(['id_minsal' => '702', 'name' => 'Singapur']);
      Country::Create(['id_minsal' => '760', 'name' => 'Siria']);
      Country::Create(['id_minsal' => '706', 'name' => 'Somalia']);
      Country::Create(['id_minsal' => '144', 'name' => 'Sri lanka']);
      Country::Create(['id_minsal' => '710', 'name' => 'Sudáfrica']);
      Country::Create(['id_minsal' => '736', 'name' => 'Sudán']);
      Country::Create(['id_minsal' => '752', 'name' => 'Suecia']);
      Country::Create(['id_minsal' => '756', 'name' => 'Suiza']);
      Country::Create(['id_minsal' => '740', 'name' => 'Surinám']);
      Country::Create(['id_minsal' => '744', 'name' => 'Svalbard y Jan Mayen']);
      Country::Create(['id_minsal' => '748', 'name' => 'Swazilandia']);
      Country::Create(['id_minsal' => '762', 'name' => 'Tayikistán']);
      Country::Create(['id_minsal' => '764', 'name' => 'Tailandia']);
      Country::Create(['id_minsal' => '158', 'name' => 'Taiwán']);
      Country::Create(['id_minsal' => '834', 'name' => 'Tanzania']);
      Country::Create(['id_minsal' => '086', 'name' => 'Territorio Británico del Océano Índico']);
      Country::Create(['id_minsal' => '260', 'name' => 'Territorios Australes y Antárticas Franceses']);
      Country::Create(['id_minsal' => '626', 'name' => 'Timor Oriental']);
      Country::Create(['id_minsal' => '768', 'name' => 'Togo']);
      Country::Create(['id_minsal' => '772', 'name' => 'Tokelau']);
      Country::Create(['id_minsal' => '776', 'name' => 'Tonga']);
      Country::Create(['id_minsal' => '780', 'name' => 'Trinidad y Tobago']);
      Country::Create(['id_minsal' => '788', 'name' => 'Tunez']);
      Country::Create(['id_minsal' => '795', 'name' => 'Turkmenistán']);
      Country::Create(['id_minsal' => '792', 'name' => 'Turquía']);
      Country::Create(['id_minsal' => '798', 'name' => 'Tuvalu']);
      Country::Create(['id_minsal' => '804', 'name' => 'Ucrania']);
      Country::Create(['id_minsal' => '800', 'name' => 'Uganda']);
      Country::Create(['id_minsal' => '858', 'name' => 'Uruguay']);
      Country::Create(['id_minsal' => '860', 'name' => 'Uzbekistán']);
      Country::Create(['id_minsal' => '548', 'name' => 'Vanuatu']);
      Country::Create(['id_minsal' => '862', 'name' => 'Venezuela']);
      Country::Create(['id_minsal' => '704', 'name' => 'Vietnam']);
      Country::Create(['id_minsal' => '876', 'name' => 'Wallis y Futuna']);
      Country::Create(['id_minsal' => '887', 'name' => 'Yemen']);
      Country::Create(['id_minsal' => '262', 'name' => 'Yibuti']);
      Country::Create(['id_minsal' => '894', 'name' => 'Zambia']);
      Country::Create(['id_minsal' => '716', 'name' => 'Zimbabue']);
    }
}
