<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MedicalProgrammer\Activity;

class HmActivitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Activity::Create(['id_activity' => 1,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Consulta Nueva de especialidad','description'=>'Es la primera atención generada por un episodio de una enfermedad, mediante la que se puede o no dar resolución a un problema de salud. Cada primera atención de un paciente generado por una interconsulta es una consulta nueva por la especialidad que realiza la atención, independiente que el paciente haya sido atendido en otra ocasión en la especialidad.', 'performance'=>1,'programmable'=>1]);
      Activity::Create(['id_activity' => 2,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Consulta Control de especialidad','description'=>'Son las atenciones posteriores a la primera consulta por un mismo problema de salud cuya finalidad es completar el estudio, tratamiento y/o seguimiento.', 'performance'=>1,'programmable'=>1]);
      Activity::Create(['id_activity' => 3,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Atención de Servicio de Urgencia (Desde Atención Ambulatoria).','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 4,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Procedimientos especialidad','description'=>NULL, 'performance'=>0,'programmable'=>1]);
      Activity::Create(['id_activity' => 5,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Turno (Todas las unidades hospitalarias)','description'=>'urgencia gineco-obstetrica', 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 6,'mother_activity_id' => 1,'activity_type_id'=>1,'activity_name'=>'Pabellon Cirugía Mayor Ambulatoria','description'=>'Corresponde a todo acto quirúrgico mayor, que se realiza en un pabellón ambulatorio o central, luego del cual el usuario, pasado un período de recuperación, vuelve a su domicilio el mismo día. Se considerarán también CMA los casos en que el paciente pernocte en el establecimiento siempre que su estadía sea menor o igual a 24 horas y que ésta se realice en sala de recuperación u otra destinada a este fin, y no en una cama hospitalaria.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 7,'mother_activity_id' => 1,'activity_type_id'=>1,'activity_name'=>'Pabellon Cirugía Mayor','description'=>'comprende procedimientos quirúrgicos que implican manipulación de órganos vitales y/o cuya incisión permite acceder a grandes cavidades y/o cavidades o estructuras estériles (incluye cirugía Máxilo – facial). Requiere de un equipo quirúrgico y anestesista especializado, se realiza siempre en pabellón quirúrgico. Demanda preparación preoperatoria, sedación, anestesia general y/o regional, eventualmente local. Utiliza recuperación post quirúrgica, puede necesitar apoyo a funciones vitales.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 8,'mother_activity_id' => 1,'activity_type_id'=>1,'activity_name'=>'Pabellon Cirugía Menor','description'=>'Comprende procedimientos quirúrgicos sencillos y habitualmente de corta duración, realizados sobre tegumentos o estructuras fácilmente accesibles. Puede ser realizada con anestesia local, requiriendo mínima medicación preoperatoria, puede ser realizada en pabellón habilitado para estos fines, es de bajo riesgo vital y presenta escasas complicaciones.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 9,'mother_activity_id' => 1,'activity_type_id'=>1,'activity_name'=>'Pabellon Cirugía Obstetrica','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 10,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Visita a sala Hospitalizado','description'=>'Es la atención de médicos especialistas que realizan a pacientes hospitalizados, en sala. Para ello se utilizará como fuente de información, los registros de hospitalizados que mantienen las Unidades Funcionales', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 11,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Consultoría en salud','description'=>'Es una actividad conjunta y de colaboración permanente entre el equipo de especialidad de atención secundaria y/o terciaria con el equipo de salud de atención primaria, con la  2 finalidad de garantizar la continuidad de cuidados de la población usuaria, potenciar la capacidad resolutiva del nivel primario y mejorar la referencia y contra referencia de personas entre ambos niveles de atención. Se puede realizar con o sin la persona usuaria presente. Se requiere esta actividad cuando: − No hay suficiente claridad en el diagnóstico de la persona usuaria. − A pesar de todos los esfuerzos, no se logran los objetivos del Plan de Cuidados Integrales (PCI). − Se requiere evaluar la pertinencia y priorización de la derivación al nivel de especialidad. − La persona usuaria ha sido contra referida desde el nivel especializado y uno o ambos equipos consideran necesario abordar en conjunto la situación de complejidad para mejorar la continuidad del cuidado. Cuando la entrega de la prestación se realiza a distancia mediante la participación de los profesionales, quienes logran comunicación a través de Tecnologías de Información y Comunicación, le denominamos Tele consultoría. El objetivo principal de la Consultoría es la transmisión de conocimientos entre los equipos, de esta acción se desprende además la resolución de un problema de salud de una persona usuaria.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 12,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Ronda otro establecimiento','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 13,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Teleconsulta nueva de especialidad','description'=>'Corresponde a la atención profesional otorgada por el médico especialista a una persona usuaria, en un lugar destinado para esos fines. Esta prestación que se realiza ambulatoriamente incluye anamnesis, examen físico, hipótesis diagnostica, con o sin prescripción de exámenes o medidas terapéuticas. Se entenderá incluido en ella algunos procedimientos mínimos y habituales en una consulta médica tales como medición de presión arterial, otoscopia, medición de peso y talla. La entrega de esta prestación se realiza a distancia mediante la participación de dos profesionales médicos, quienes logran comunicación a través de Tecnologías de Información y Comunicación, aportando información de la persona usuaria que puede o no estar presente, generándose de esa interacción un planteamiento diagnóstico y terapéutico', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 14,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Teleconsulta control de especialidad','description'=>'Corresponde a la atención profesional otorgada por el médico especialista a una persona usuaria, en un lugar destinado para esos fines. Esta prestación que se realiza ambulatoriamente incluye anamnesis, examen físico, hipótesis diagnostica, con o sin prescripción de exámenes o medidas terapéuticas. Se entenderá incluido en ella algunos procedimientos mínimos y habituales en una consulta médica tales como medición de presión arterial, otoscopia, medición de peso y talla. La entrega de esta prestación se realiza a distancia mediante la participación de dos profesionales médicos, quienes logran comunicación a través de Tecnologías de Información y Comunicación, aportando información de la persona usuaria que puede o no estar presente, generándose de esa interacción un planteamiento diagnóstico y terapéutico', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 15,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Teleconsulta de especialidad hospitalizado','description'=>'Corresponde a la atención profesional otorgada por el médico especialista a una persona usuaria, en un lugar destinado para esos fines. Esta prestación que se realiza ambulatoriamente incluye anamnesis, examen físico, hipótesis diagnostica, con o sin prescripción de exámenes o medidas terapéuticas. Se entenderá incluido en ella algunos procedimientos mínimos y habituales en una consulta médica tales como medición de presión arterial, otoscopia, medición de peso y talla. La entrega de esta prestación se realiza a distancia mediante la participación de dos profesionales médicos, quienes logran comunicación a través de Tecnologías de Información y Comunicación, aportando información de la persona usuaria que puede o no estar presente, generándose de esa interacción un planteamiento diagnóstico y terapéutico', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 16,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Visita Domiciliaria','description'=>'Es una modalidad de prestación de salud en domicilio, dirigida a las personas y sus familias en riesgo biopsicosocial, basada en la construcción de una relación de ayuda entre el equipo de salud interdisciplinario y la familia. Esta atención permite detectar, valorar, apoyar y controlar los problemas de salud del individuo y la familia, potenciando la autonomía y mejorando la calidad de vida de las personas, se inserta en el marco de un plan de acción definido por el equipo de salud de cabecera, con objetivos específicos que comandan las acciones correspondientes, los que son expuestos a la familia durante el proceso de atención, y son construidos entre el equipo de salud y la familia y/o cuidadores y realizados por profesionales y/o técnicos con las competencias requeridas. En “Visitas Domiciliarias Integrales” se registra la actividad realizada por un profesional, dos o más profesionales, un profesional y técnico paramédico. No son Visitas Domiciliarias las verificaciones de domicilio y las citaciones de horas.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 17,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Gestión de Casos','description'=>'Coordinación clínico administrativo que articula los procesos necesarios para garantizar la atención integral de salud (acompañamiento y seguimiento, trabajo en red a cargo de un profesional que actúa como facilitador del proceso asistencial)', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 18,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Consulta Abreviada Médica','description'=>'Corresponde a la ejecución de acciones destinadas a repetir receta de personas usuarias que se están atendiendo en el establecimiento, o a la lectura de exámenes o revisión de informes. Dicha actividad no es considerada como consulta propiamente tal ya que, por lo general, no existe interacción directa del profesional. Las acciones también pueden realizarse mediante tecnologías de información y comunicaciones, constituyéndose de esta forma una Teleconsulta Abreviada.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 19,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Procedimientos Imagenológicos (Médico)','description'=>'Es la atención mínimamente invasiva proporcionada por un médico imagenólogo  con el objetivo de realizar procedimiento de apoyo diagnóstico o terapéutic', 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 20,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Interconsulta en sala','description'=>'ginecologia y obstetricia', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 21,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Comité Clínico','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 22,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Comité Oncológico','description'=>'Reunión multidisciplinaria de un conjunto de especialistas y subespecialistas quede manera sistemática evalúan antecedentes clínicos, y en conjunto plantean el plan terapéutico según estadificación y protocolos vigentes. Facilita la toma de decisiones en situaciones complejas al reunir en una sesión a los especialistas claves de una patología determinada', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 23,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Reunión Clínica','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 24,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Reunión Técnica Administrativa','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 25,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Otros Actividades Clínicas','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 26,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Gestión Organizacional (Administrativo/ Jefatura)','description'=>'ginecologia y obstetricia', 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 27,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Investigación','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 28,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Docencia','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 29,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Otras Actividades No Clínicas','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 30,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Hospitalización Domiciliaria','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 31,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Comite Articulador de Continuidad de Cuidados (SM/ REHAB)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 32,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Psicoterapia Grupal (SM)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 33,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Psicoterapia Familiar (SM)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 34,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Intervención Psicosocial Grupal (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 35,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Rescate no presencial (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 36,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Visita Integral de Salud Mental (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 37,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Actividad Comunitaria (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 38,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Actividades con organizaciones de usuarios y familiares (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 39,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Colaboración y formación con grupos de autoayuda (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 40,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Coordinación con Equipos de la red de salud (PCI/ SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 41,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Trabajo sectorial (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 42,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Trabajo intersectorial (SM)','description'=>'INFERFAZ', 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 43,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Actividades de cuidado del equipo (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 44,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Comité de ingreso a atención cerrada (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 45,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Consejo Técnico de Salud Mental en el Servicio de Salud (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 91,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Comité por Telemedicina','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 92,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Consulta Ingreso Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 93,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Consulta Control Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 94,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Intervención Familiar Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 95,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Intervención Psicosocial Grupal Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 96,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Visita Integral de Salud Mental Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 104,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Tele consultoría (Telemedicina)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 105,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Tele consulta abreviada (Telemedicina) ','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 106,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Atención remota: consulta nueva','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 107,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Atención remota: consulta control','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 108,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Atención remota: consulta abreviada','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 109,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Atención remota: consultoría','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 110,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Teletrabajo no programado','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 111,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Evaluación Intermedia remota','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 112,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Sesión de rehabilitación vía remota (Telerehabilitación)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 113,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Educación remota a usuario y/o cuidador','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 114,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Rehabilitación domiciliaria','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 47,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consultas totales (SM)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 3,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención de Servicio de Urgencia (Desde Atención Ambulatoria).','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 48,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Procedimientos (apoyo en procedimientos médicos y propios)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 5,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Turno (Todas las unidades hospitalarias)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 49,'mother_activity_id' => 1,'activity_type_id'=>2,'activity_name'=>'Pabellon','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 11,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consultoría en salud','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 12,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Ronda otro establecimiento','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 16,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Visita Domiciliaria','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 17,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Gestión de Casos','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 50,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consulta Abreviada no Médica','description'=>'Es una breve atención proporcionada por el profesional no médico para dar solución específica a un problema de salud, comprende acciones destinadas a valoración de antecedentes, apoyo diagnóstico o refuerzo de indicaciones.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 51,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Contrareferencia','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 52,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Taller Grupal','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 53,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención de Enlace o Interconsulta a sala','description'=>'Atención otorgada por la profesional enfermera(o) de la atención ambulatoria de especialidad, en las unidades de hospitalizados o urgencias, con el fin de contactar, evaluar o realizar seguimiento a un paciente y coordinar en conjunto con enfermera de la unidad la intervención de enfermería y plan de cuidado correspondiente', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 110,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Teleconsulta nueva (Telemedicina)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 111,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Teleconsulta control (Telemedicina)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 54,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Educación Individual','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 21,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Comité clínico','description'=>'Corresponde a la reunión entre distintos profesionales de uno o más equipos que evalúan antecedentes clínicos de una persona usuaria y en conjunto plantean el Plan de Cuidados Integrales según protocolos y guías clínicas vigentes. Facilita la toma de decisiones en situaciones complejas al reunir a los profesionales claves de un problema de salud determinado. La decisión queda registrada en el documento de Resolución de Comité. Esta reunión se realiza entre profesionales de una misma o diferente especialida', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 22,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Comité Oncológico','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 23,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Reunión Clínica','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 24,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Reunión Técnica Administrativa','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 25,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Otros Actividades Clínicas','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 26,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Gestión Organizacional (Administrativo/ Jefatura)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 27,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Investigación','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 28,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Docencia','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 29,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Otras Actividades No Clínicas','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 30,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Hospitalización Domiciliaria','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 55,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Conserjeria en salud MATRONA','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 56,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención Nutricional Intensiva (ANI)','description'=>'Atención Nutricional Intensiva Ambulatoria (ANI) Pediátrica - Adulto: Consulta nutricional ambulatoria u hospitalaria a usuarios que requieren soporte nutricional vía enteral o parenteral, dado que el usuario con tracto gastrointestinal funcionante o no funcionante, no pueda o no deba o no quiera ingerir alimentos en cantidades suficientes para mantener un desarrollo pondo estatura y nutricional adecuado.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 57,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención Nutricional en Sala','description'=>'Atención de nutricionista a paciente hospitalizado para establecer objetivos de intervención nutricional en conjunto con nutricionista de atención cerrada.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 58,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Educación nutricional establecimiento o/y espacios públicos.','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 59,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Evaluación inicial','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 60,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Evaluación intermedia','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 61,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Sesiones de Rehabilitación','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 62,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Psicodiagnostico','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 63,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Psicoterapia Individual','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 64,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Psicoterapia Familiar','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 65,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención Medicina Transfusional por TM','description'=>'Corresponde al proceso de selección y evaluación de aptitud para donar sangre o células sanguíneas, realizado por un tecnólogo médico u otro profesional capacitado. El estándar ministerial establece un proceso de gestión de agenda previa para coordinar la atención de donantes de sangre total y por aféresis, con un rendimiento mínimo de 6 entrevistas de selección a donantes por hora de trabajo. El proceso de terapia transfusional también es desarrollado por profesionales Tecnólogos Médicos, pero no puede ser agendado ni programado previamente, dado que responde a la demanda en tiempo real. Por último, las actividades de profesionales Tecnólogos Médicos relacionadas con la entrega de resultados confirmados a pacientes/donantes, también pueden ser agendadas y programadas según el protocolo y necesidad del establecimiento', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 66,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Examen Imagenologico por TM','description'=>'Es la atención proporcionada por tecnólogo médico a un paciente derivado por un profesional con el propósito de realizar examen de apoyo diagnóstico de Imagenología', 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 67,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Examen Laboratorio por TM','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 68,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Examen APA por TM','description'=>'Servicio otorgado por un laboratorio de Anatomía Patológica, cuyo objetivo es apoyar el estudio diagnóstico de una determinada patología, a través de una variedad de exámenes tales como: biopsias, citologías, histoquímica, inmunohistoquímica, inmunofluorescencia, biología molecular, microscopía electrónica, citogenética en tejidos, autopsias, entre otros en los cuales es realizado por profesional Tecnólogo Médico', 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 69,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Otros Procedimientos realizados por TM','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 70,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Disp. y validación de prescripción en AA','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 71,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Disp. y validación de prescripción en AC','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 72,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Disp. y validación de prescripción en URG','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 73,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Disp. directa especificos','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 74,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Registro de recetas','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 75,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Preparados magistrales y/o oficinales No esteril','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 76,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Preparados magistrales y/o oficinales Esteril','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 77,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Fraccionamiento de envases','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 78,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Reenvasado de unidosis','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 79,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Conciliación farmacoterapeutica','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 80,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Revisión de la medicación','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 81,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Seguimiento farmacoterapéutico','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 82,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Educación farmacoterapeutica','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 83,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Monitorización terapeutica de farmacos','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 84,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Notificación de reacciones adversas de medicamentos','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 85,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Notificación de eventos adversos asociados de medicación','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 86,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Notificación de denuncias de calidad','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 87,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Educaciones grupales (usuarios y equipo de salud )','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 88,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Inventario','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 89,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Programacion, gestion de adquisición y registro.','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 90,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Secretario de comité de farmacia y técnico','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 91,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Comité por Telemedicina','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 97,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consulta de Ingreso por Equipo Salud Mental','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 98,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Comité Articulador de Continuidad de Cuidados','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 99,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Comité de ingreso a atención cerrada (incluye Hospital de Día y UHCIP)(SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 92,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consulta Ingreso Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 93,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consulta Control Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 94,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Intervención Familiar Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 95,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Intervención Psicosocial Grupal Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 96,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Visita Integral de Salud Mental Hospital de Día y UHCIP (SM)','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 100,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consultas CONTROL POR PROFESIONAL  (SM)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 101,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consultas NUEVAS (ESPECIALIDAD)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 102,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Consultas CONTROL (ESPECIALIDAD)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 103,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Contra referencia asistida','description'=>'Actividad conjunta y de colaboración permanente entre enfermera(o) de especialidad y el equipo de enfermería de atención primaria, con el fin de mantener la continuidad de cuidados de la población usuaria.', 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 104,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Tele consultoría (Telemedicina)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 105,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Tele consulta abreviada (Telemedicina)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 106,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención remota: consulta nueva','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 107,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención remota: consulta control','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 108,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención remota: consulta abreviada','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 109,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Atención remota: consultoría','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 110,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Teletrabajo no programado','description'=>NULL, 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 111,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Evaluación Intermedia remota','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 112,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Sesión de rehabilitación vía remota (Tele rehabilitación)','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 113,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Educación remota a usuario y/o cuidador','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 114,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Rehabilitación domiciliaria','description'=>NULL, 'performance'=>1,'programmable'=>0]);
      Activity::Create(['id_activity' => 0,'mother_activity_id' => 2,'activity_type_id'=>1,'activity_name'=>'Colación','description'=>'Corresponde a la colación de contratos 44 hrs.', 'performance'=>0,'programmable'=>0]);
      Activity::Create(['id_activity' => 0,'mother_activity_id' => 2,'activity_type_id'=>2,'activity_name'=>'Colación','description'=>'Corresponde a la colación de contratos 44 hrs.', 'performance'=>0,'programmable'=>0]);

    }
}
